### ISSUE TITLE
Randomly pausing (?) during game

### ISSUE THREAD

**Issue by badzi3wiak** [Franticware/usb-to-playstation-mouse#4]
Hey!
Did anyone face issue when game is being randomly paused? In that case it's about Red Alert Retaliation. I made 2 adaptors and it's the same behaviour/issue with Dell usb mouse.
Any idea?

**Comment by badzi3wiak** [comment]
update - tested adapter with Time Crisis and here it's working fine, so seems like some bug (?) with specific title(s)...

**Comment by Franticware** [comment]
I had similar issue with Quake with some older version of my firmware. The issue was with controller bus not being released at the right moment (it is shared with memory card for example). Apparently it is still not quite right with some more timing sensitive games and I will have to look into it eventually. Thanks for the report.

**Comment by gentleben** [comment]
Firstly, thanks very much for this project! I'll upload some pics of my build once I've put some shrink tubing around it.

I've seen the game pausing issue in Red Alert Retaliation and also in Lemmings. This video shows how the mouse seems to disconnect and connect very quickly as I drag the play area around, intermittently showing the message "No controller in controller port 1".

https://ln5.sync.com/dl/ba7b9efe0/9cfydiqt-f5tetjxf-qekftnjc-w4gw3kt4

Not sure if this is helpful, but thought it might give you some clues.

**Comment by Franticware** [comment]
I was able to replicate the issues with Red Alert and Lemmings. I will probably have to obtain a real PS mouse to analyze how the communication should work exactly. Too bad those are so rare and expensive.

**Comment by Franticware** [comment]
Fixed, check the 20240414 release.

**Comment by gentleben** [comment]
Thanks for the very quick fix. Excellent wortk! :-) The latest release fixes the controller disconnect issues I had in the Command and Conquer games. I still see the issue when I scroll the playfield in Lemmings, but that's not really an issue for me because I don't play Lemmings on my PS1. Thanks again!

**Comment by Franticware** [comment]
Do you use US, or EU version of Lemmings?

**Comment by gentleben** [comment]
I usually use US (NTSC) games. When I tried EU Lemmings with the latest release (not the tweaked timing one you posted), it worked flawlessly - I couldn't reproduce the issue.

When I tried the tweaked-timing firmware, it was more difficult to reproduce the issue in US Lemmings, but unfortunately I could also reproduce the issue in EU Lemmings and also again in US Command and Conquer.

My PS1 has an XStation installed. The model number is SCPH-5501. I've also installed a [DFO](https://www.consolesunleashed.com/product/sony-playstation-dual-frequency-oscillator-mod-kit/) and [X-Reset mod](https://www.consolesunleashed.com/product/sony-playstation-x-reset-mod-kit/).

I tried with and without a memory card, but that made no difference.

The exact steps to reproduce the issue are:
Plug the mouse adapter and mouse
Turn on the PS1
Choose US Lemmings from the menu
Start a new game
When the game starts, moving the play area back and forth using the while rectangle in the bottom right of the screen, like the video above shows (https://ln5.sync.com/dl/ba7b9efe0/9cfydiqt-f5tetjxf-qekftnjc-w4gw3kt4).
The game will go to paused.

I only see the issue in US Lemmings, so it's really not a major issue for me. It works great in the games I want to play, so thank you for the great work!

**Comment by Franticware** [comment]
Our setups are remakably similar :) I guess the only difference is that you have NTSC console and mine is PAL. XStation can work around that of course.

When you start new Lemmings game, does e.g. the level or difficulty selected make a difference?

I have a few more ideas as what to tweak, but very little time at this point. Once I get to it, I will try to provide more tweaked firmware variants to try (if you are willing to try them with NTSC Lemmings - no pressure).

I guess it is not all bad that I can't reproduce this issue. It might mean it is quite rare. Your ability to reproduce this on your configuration is valuable.

**Comment by gentleben** [comment]
Do also have a DFO installed? My console is a PAL one. I just stick to NTSC games as I have a RAD2X which scales NTSC resolution better (at least on my monitor). I guess the console outputs NTSC properly with the DFO installed?

The issue in US Lemmings seems to be consistent, regardless of difficulty or level.

Yep, I'm happy to try out firmware variants and feed back.

I'm glad it's a rare issue. I've not noticed an issue with anything other than US Lemmings, which I never play anyway - I have my trusty old Amiga for that. :-)

**Comment by Franticware** [comment]
DFO seems like something I could definitely use, thanks for the tip.

**Comment by Franticware** [comment]
Today I finally received DFO and installed it right away. Indeed, now I am able to reproduce the issue with NTSC Lemmings. I should be able to fix it eventually.

**Comment by gentleben** [comment]
That's great. Reproducing the issue is sometimes half the battle. Also, it's good to know that it's not just my PS1. :-)

**Comment by Franticware** [comment]
I have started a new repository for the successor project: https://github.com/Franticware/usb-to-ps1-mouse-pro

I am focused on that, but I might backport some fixes to this soon-to-be-deprecated repository in the future.

**Comment by Franticware** [comment]
I have quickly backported significant changes from the upcoming https://github.com/Franticware/usb-to-ps1-mouse-pro . There is a new release 20240607 as a result. It should address the game compatibility issues. I have done only limited testing due to time constraints (NTSC Lemmings, PAL C&C) and I thought I would leave the rest up to you all. It should also give some basic idea about the improvements the new project is going to bring.

**Comment by gentleben** [comment]
The latest update is great. I can still get NTSC Lemmings to get the controller disconnected error message, but I have to try much harder now. It would be rare for that to happen during normal gameplay. Everything else I've tried is flawless. Thanks again for a great piece of software!

**Comment by Franticware** [comment]
How about https://github.com/Franticware/usb-to-playstation-mouse/releases/tag/20240909 ?

**Comment by gentleben** [comment]
I have to try very hard now with the latest version to get NTSC Lemmings to pause due to controller disconnect. It's a very specific issue that only occurs when the gameplay area is moved rapidly back and forth in NTSC Lemmings running on a PAL PS1 with a DFO fitted, and it isn't really a problem for gameplay as the game just goes to Paused. It's not something that anyone "normal" will really do very often. 😃 . With all other PS1 mouse games I've tried, it's working great!!

Here's a video of me trying to replicate the issue:

https://ln5.sync.com/dl/647b06720/u8ai6w4p-cvybqxb2-68362s4b-8f6aq9uw

**Comment by Franticware** [comment]
I have reproduced it with usb-to-ps1-mouse-pro as well:
https://www.youtube.com/live/aHxFAbpGnSA?t=200s

**Comment by gentleben** [comment]
I think they call this an "edge case". :smile:
